### ISSUE TITLE
Please make a InSim Dissector!

### ISSUE THREAD

**Issue by Dygear** [theangryangel/wireshark-lfs-dissectors#1]
Please make an InSim Dissector as well.

**Comment by theangryangel** [comment]
I'm sure something could be arranged :)

**Comment by theangryangel** [comment]
I dont know whats more depressing. LFS' pace of development or my constant distraction after starting a project :laughing: 

Edit: OK. Never update a github issue 10 minutes after awaking up.. I can math. I swear :sob:
